// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmT1W2wAy9boeKUjP1xvs2uIMzEpJyRxg',
    appId: '1:53006197508:web:b2fca36025254759e36651',
    messagingSenderId: '53006197508',
    projectId: 'learningapp-ee6cb',
    authDomain: 'learningapp-ee6cb.firebaseapp.com',
    storageBucket: 'learningapp-ee6cb.firebasestorage.app',
    measurementId: 'G-KNGCKYHBCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr4lajgHCVYgcklggNZ0MjSEn1L5JTtNw',
    appId: '1:53006197508:android:73b65afc31e691abe36651',
    messagingSenderId: '53006197508',
    projectId: 'learningapp-ee6cb',
    storageBucket: 'learningapp-ee6cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrbS6X_-JIDeHJOklpwkVdBW4ZQgwlRYk',
    appId: '1:53006197508:ios:2570cc5be0e20592e36651',
    messagingSenderId: '53006197508',
    projectId: 'learningapp-ee6cb',
    storageBucket: 'learningapp-ee6cb.firebasestorage.app',
    iosBundleId: 'com.example.pathshala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrbS6X_-JIDeHJOklpwkVdBW4ZQgwlRYk',
    appId: '1:53006197508:ios:2570cc5be0e20592e36651',
    messagingSenderId: '53006197508',
    projectId: 'learningapp-ee6cb',
    storageBucket: 'learningapp-ee6cb.firebasestorage.app',
    iosBundleId: 'com.example.pathshala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmT1W2wAy9boeKUjP1xvs2uIMzEpJyRxg',
    appId: '1:53006197508:web:fe371030d0963276e36651',
    messagingSenderId: '53006197508',
    projectId: 'learningapp-ee6cb',
    authDomain: 'learningapp-ee6cb.firebaseapp.com',
    storageBucket: 'learningapp-ee6cb.firebasestorage.app',
    measurementId: 'G-M3PLQFXZVQ',
  );

}